const country = []

country[0] = "Afganistan"
country[1] = "Arabia Saudyjska"
country[2] = "Armenia"
country[3] = "Azerbejdzan"
country[4] = "Bahrajn"
country[5] = "Bangladesz"
country[6] = "Brunei"
country[7] = "Bhutan"
country[8] = "Chiny"
country[9] = "Cypr"
country[10] = "Filipiny"
country[11] = "Gruzja"
country[12] = "Indie"
country[13] = "Indonezja"
country[14] = "Irak"
country[15] = "Iran"
country[16] = "Izrael"
country[17] = "Japonia"
country[18] = "Jemen"
country[19] = "Jordania"
country[20] = "Kambodża"
country[21] = "Katar"
country[22] = "Kazachstan"
country[23] = "Kirgistan"
country[24] = "Korea Południowa"
country[25] = "Korea Północna"
country[26] = "Kuwejt"
country[27] = "Laos"
country[28] = "Liban"
country[29] = "Malediwy"
country[30] = "Malezja"
country[31] = "Mjanma"
country[32] = "Mongolia"
country[33] = "Nepal"
country[34] = "Oman"
country[35] = "Pakistan"
country[36] = "Rosja"
country[37] = "Singapur"
country[38] = "Sri Lanka"
country[39] = "Syria"
country[40] = "Tadżykistan"
country[41] = "Tajlandia"
country[42] = "Timor Wschodni"
country[43] = "Turcja"
country[44] = "Turkmenistan"
country[45] = "Uzbekistan"
country[46] = "Wietnam"
country[47] = "Zjednoczone Emiraty Arabskie"

const flag = document.querySelector("#flag")

for(i=0; i<country.length; i++)
{
    flag.innerHTML += '<img src="img/'+country[i]+'.svg" alt="flaga" style="width: 300px; height: 200px; margin: 5px;">'
}